//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string title { get; set; }
        public string Descrption { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual usertable usertable { get; set; }
    }
}
